### ISSUE TITLE
DFW.pm shutting down?

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#101]
@tommybutler hey, should I deactivate your group? 

http://mail.pm.org/pipermail/dfw-pm/2017-January/000788.html

**Comment by tommybutler** [comment]
Please give it a couple days to see if someone is willing to step in.  So far, no takers, but it's the weekend.  I'll follow up on Tues.

**Comment by jhannah** [comment]
No rush. We'd only be worried after a year or so. :)

**Comment by tommybutler** [comment]
OK you're good to shut it down now.  Thanks!
