### ISSUE TITLE
Change domain endpoint for Curitiba Perl Mongers

### ISSUE THREAD

**Issue by aramisf** [perlorg/www.pm.org#102]
Hello,
Can you please update the DNS for http://curitiba.pm.org domain to start pointing to http://curitiba-pm.github.io?

Thanks in advance.

**Comment by jhannah** [comment]
Do you want a DNS CNAME, or an Apache redirect from our server to yours?

**Comment by aramisf** [comment]
Sorry for my lack of clarity.

We need the http://curitiba.pm.org address to keep existing, but instead of pointing to its current url, we'd like it to point to http://curitiba-pm.github.io/.

The address bar in the browser should still show http://curitiba.pm.org/.
This is a DNS CNAME, isn't it? Sorry for my ignorance.

**Comment by jhannah** [comment]
Oh, sorry, it's github -- my bad. :) DNS CNAME should work fine.

I was confused due to another recent group whose hosting provider... @blahblahblah :)

I submitted a DNS request for you. It should take effect in a day or so.

**Comment by aramisf** [comment]
Thank you @jhannah 😄

**Comment by aramisf** [comment]
I've just checked the url, and it has been updated:

```
curitiba.pm.org.	7200	IN	CNAME	curitiba-pm.github.io.
```

Thank you @jhannah, I'm closing the issue.
