### ISSUE TITLE
Can't login on WebDAV to update website :(

### ISSUE THREAD

**Issue by xsawyerx** [perlorg/www.pm.org#103]
```
Could not open collection:
Certificate verification error: signed using insecure algorithm
```

**Comment by jhannah** [comment]
#37 speaks to this. Does that conversation help?

**Comment by xsawyerx** [comment]
Yes, it did!

For the record: I have downloaded with `openssl` the certificate, copied it to the system one and ran (under Debian) `update-ca-certificates`. It's good now. :)

Thanks!!
