### ISSUE TITLE
New Admins for Purdue-PM mailing list

### ISSUE THREAD

**Issue by jacoby** [perlorg/www.pm.org#107]
I don't know who the moderator is for http://mail.pm.org/mailman/admindb/purdue-pm is, probably Mark Senn, but it SHOULD be me and/or Joe "Gizmo" Kline.

Please make that change?

**Comment by jhannah** [comment]
There is currently a single admin: jacoby.david@gmail.com

http://mail.pm.org/mailman/admin/purdue-pm

If that's wrong, or you need me to reset the admin password, let me know.

**Comment by jacoby** [comment]
A password reset please

**Comment by jhannah** [comment]
Email sent to above gmail. Please close this issue if you're all set now. Thanks!

**Comment by jacoby** [comment]
All is well. Thank you.
