### ISSUE TITLE
D/FW transfer

### ISSUE THREAD

**Issue by rdhughes** [perlorg/www.pm.org#110]
I've been speaking with Tommy Butler who announced a few months ago that he and John Fields have to drop running the D/FW Perl Mongers chapter due to other commitments taking over their free time. Therefore, Tommy has agreed to transfer stewardship of the group to me, and I'll be taking over as president of the chapter.

Please let me know what other information is needed to move this forward.

I can also be reached at robert.d.hughes at gmail dot com.

Thanks

**Comment by jhannah** [comment]
Hi Robert. So we just need to update https://github.com/perlorg/www.pm.org/blob/master/perl_mongers.xml#L556-L576

If you want to send a pull request I'll merge it. Or if you prefer I do it, I'd be happy to. Thanks!

**Comment by rdhughes** [comment]
For now, it's probably best if you do it. Never really used GIT though I'm sure it's not any harder than SVN.

**Comment by jhannah** [comment]
http://www.pm.org/groups/24.html

**Comment by tommybutler** [comment]
@jhannah can we get the DNS record for dfw.pm.org pointed to 104.167.8.103 ??
@rdhughes  please contact me via phone for credentials to modify the site html files.

**Comment by jhannah** [comment]
DNS request # 131711 created. It should take effect in a day or so.

**Comment by jhannah** [comment]
Looks like DNS is working.
