### ISSUE TITLE
Can't run bin/xml against a symlink anymore?

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#112]
I'm entirely mystified by this. I've been using a symlink for this for ... a decade? That chunk of Template hasn't changed in 13 years, perl 5.26 and 5.18 agree that `-d www` (a symlink) is false, `bin/xml` hasn't changed... @rspier any idea?

```
➜  jhannah-Air:www.pm.org git:(master) ✗ ls -al www
lrwxr-xr-x  1 jhannah  staff  25 Oct 20  2014 www -> /Volumes/admin/groups/www
➜  jhannah-Air:www.pm.org git:(master) ✗ perl bin/xml
mkdir www: File exists at /Users/jhannah/perl5/perlbrew/perls/perl-5.26.0/lib/site_perl/5.26.0/darwin-2level/Template.pm line 187.
```

**Comment by jhannah** [comment]
Did the WebDAV mount software change so Perl used to see it as a directory, but perl 5.26.0 does not?

**Comment by jhannah** [comment]
Created #113 as a work-around, if anybody has any feedback.

**Comment by rspier** [comment]
No idea.  

This is a good reminder that we need to change how the www.pm.org hosting works, WebDAV is going away real soon now.

**Comment by jhannah** [comment]
@rspier ok. Well, I can host it on my Linode if you want. Or give me scp access to a box of your choice?

**Comment by rspier** [comment]
I just sent you an email with details about a quick and dirty git solution.

**Comment by jhannah** [comment]
@rspier YAY! This is WAY faster than the old way. It used to take ~60s to flush because of all the WebDAV back and forth. I pushed to #113 and to your private repo to see if it sticks. Thanks!
