### ISSUE TITLE
Add <github_username> of tsars to perl_mongers.xml?

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#115]
Hey @rspier I was thinking of putting a call out to the group leader mailing list to get all the tsars to add their github_username to our XML file. Good idea? Bad idea?

Would CPAN username be a better idea? (From which their github might be attached in metacpan API?)

**Comment by rspier** [comment]
What's the rationale for having them add it?

**Comment by jhannah** [comment]
@rspier my thought was I could highlight the group leader here in github issues w/o searching for their github user ID. Now that it's hours later I'm thinking the attempt would be more work than the time it might save me.

**Comment by rspier** [comment]
I concur.
