### ISSUE TITLE
http://www.perl.ba/ is down

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#116]
@perlba opening this issue so I don't forget. (Following up from #111 which is closed.)

**Comment by jhannah** [comment]
Hey @perlba your website is still down, so I'm deactivating your group for now.

**Comment by perlba** [comment]
@jhannah my website is up, and down as hosted from my home, and sometime I turn off server(not more than 6 hrs), but most of the time is up since date you opened issue. Last month was 24/7 on. Please activate back, or redirect it to perlba.github.io if possible.

**Comment by jhannah** [comment]
@perlba hi! Can you please add links to however people interested in Perl in your area would communicate with you? (Email list? Meetings? IRC? Twitter? We don't care what you use as long as interested people have a way to talk about Perl.)

**Comment by perlba** [comment]
@jhannah sure I can do that. As soon I make website looks on proper way, I will let you know.
