### ISSUE TITLE
kw.pm DNS is down; contact-address change

### ISSUE THREAD

**Issue by da-** [perlorg/www.pm.org#119]
Hello,
pm.org's list of groups shows kw.pm with a contact email address of 'da@coder.com' - this address is no longer active as I've sold that domain. Can you please change this to 'dada.da+kwpm@gmail.com' ? 

Also, kw.pm.org seems to have gone away- if you're still offering dns forwarding, could it be re-instantiated? I can't remember if it was a CNAME or a DNS IP record but think it might have been a CNAME to coder.com. If practical, a CNAME to xform.net would do fine. Please let me know if that's not a good solution!

Thanks for your pm support over the many years,
Daniel

**Comment by jhannah** [comment]
So you want `kw.pm.org CNAME xform.net`?

**Comment by da-** [comment]
Yes, please!
Thanks,
Daniel

**Comment by jhannah** [comment]
DNS request (#131792) submitted. It should take effect in a day or so.

**Comment by jhannah** [comment]
http://www.pm.org/groups/535.html should update in ~30 minutes.
