### ISSUE TITLE
http://brasilia.pm.org/

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#120]
Hi @djrondon. Your website is neat, but can you add links to your meetings / mailing list in plain text? We want Perl Mongers groups to be newbie friendly. :)  Thanks!

**Comment by djrondon** [comment]
Ok Jay. I'll do that. I have a new flash one to release. Ok

Thanks,

Rondon

**Comment by jhannah** [comment]
Ping! It's been a couple months, are you still around? :)

**Comment by djrondon** [comment]
Hi Jay,

Yes, I'm here.
As you can't host brasilia.pm.org, can you park the domain at my
000webhost.com/


---------------------------------------------------------------------------------------------
Your life is shaped by your mind and you become what you think.
Dhampada - Twin Verses.

2017-10-05 16:59 GMT-03:00 Jay Hannah <notifications@github.com>:

**Comment by jhannah** [comment]
We can do either:
(1) We point DNS wherever you tell us to.
(2) We Apache redirect to whatever URL you tell us to.

**Comment by jhannah** [comment]
No response, closing.

**Comment by djrondon** [comment]
Hi Jay. I'm changing to another provider because 000webhost doesn't accept
to point subdomains. :-(
I'm looking for another as fast as I can.. I'll migrate till thrusday. ok

Thanks for your comprehension.

Cheers,

Rondon


---------------------------------------------------------------------------------------------
Your life is shaped by your mind and you become what you think.
Dhampada - Twin Verses.

2017-10-24 15:28 GMT-02:00 Jay Hannah <notifications@github.com>:

**Comment by jhannah** [comment]
Cool, thanks. Let us know when you're ready. 👍

**Comment by djrondon** [comment]
Hi Jay,

You can redirect brasilia.pm.org to this dns:

*ns1.freehostingeu.com <http://ns1.freehostingeu.com>* e *ns2.freehostingeu.com
<http://ns2.freehostingeu.com>*.
ok.

Thanks.

Rondon

---------------------------------------------------------------------------------------------
Your life is shaped by your mind and you become what you think.
Dhampada - Twin Verses.

2017-10-24 18:37 GMT-02:00 Rondon <djrondon@gmail.com>:

**Comment by jhannah** [comment]
Hey @djrondon we don't delegate DNS, sorry  https://www.pm.org/faq/hosting_faq.html#dns

We can add whatever `A` records you want, and/or Apache redirect to wherever you want.

Let me know what you'd like us to do.

**Comment by djrondon** [comment]
Jay,

Can I use your space at pm.org. I can upload all the pages.. the app is
very easy.. Can I do that ?
I remember that I could do that using cadaver.. Is that correct ?

---------------------------------------------------------------------------------------------
Your life is shaped by your mind and you become what you think.
Dhampada - Twin Verses.

2017-11-14 15:59 GMT-02:00 Jay Hannah <notifications@github.com>:

**Comment by jhannah** [comment]
@djrondon we stopped hosting sites in 2014 https://www.pm.org/faq/hosting_faq.html#offered

You can host your site anywhere you want, there's a couple suggestions in that FAQ.

Let me know where I should point your DNS. Thanks!

**Comment by djrondon** [comment]
OK.. I'll read it.. thanks Jay.
