### ISSUE TITLE
Would like to migrate shanghai.pm to github pages

### ISSUE THREAD

**Issue by Hugh----** [perlorg/www.pm.org#121]
Hi there,

Could you please help redirect https://groups.pm.org/groups/shanghai/ to https://hugh----.github.io/shanghai.pm/index ?

I would like to keep the mailing list as is: http://mail.pm.org/mailman/listinfo/shanghai-pm

If you have any questions, please let me know. Thanks.

**Comment by jhannah** [comment]
@rspier I forget -- is github pages a DNS request or an Apache redirect?

**Comment by rspier** [comment]
(Sorry for the delay).

It can be either.

If they want SSL, it needs to be an Apache redirect, as github doesn't serve the pm.org cert.

**Comment by Hugh----** [comment]
@rspier Thanks for the information.
@jhannah If possible, do an Apache redirect, please. You may use https://hugh----.github.io/shanghai.pm as the destination. Thanks.

**Comment by jhannah** [comment]
@rspier hmm so how this used to work is I would WebDAV mount and then edit `config/rewritemap` ... how do I edit the Apache redirect config file nowadays?

**Comment by rspier** [comment]
Good question.  For now just ask me to do it.  As we shut down the server, we may be changing the underlying implementation.

Anyway, redirect setup.

**Comment by Hugh----** [comment]
Thanks @rspier @jhannah .
