### ISSUE TITLE
Ankara.pm

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#124]
Hi @yplog! Instead of #123, I pushed 8833260. Yours is not a new group, you're re-activating a group that was originally started in 2004. That OK?

**Comment by jhannah** [comment]
Where are you going to host ankara.pm.org? We don't offer hosting on pm.org. Everyone uses their own servers, or Github pages or whatever.

**Comment by jhannah** [comment]
I added you to the group leader email list, and created your group's Mailman list: http://mail.pm.org/mailman/listinfo/ankara-pm

**Comment by yplog** [comment]
I will host ankara.pm.org at gitlab.com. If you direct to 52.167.214.135 for this, rejoice.

**Comment by jhannah** [comment]
DNS request submitted. Should take effect in a day or so.

**Comment by jhannah** [comment]
Looks like everything is working. yay!
