### ISSUE TITLE
kc.pm.org not responding

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#125]
ping @djgoku!

**Comment by djgoku** [comment]
Hey jay! Yeah it isn't.

**Comment by jhannah** [comment]
@djgoku are you going to fix it, or should I deactivate your group for now? Thanks

**Comment by djgoku** [comment]
Good question. I am busy this weekend, but will add something to my calendar this next week to figure this out.

**Comment by djgoku** [comment]
Do you mind re-directing to this for now: https://djgoku.github.io/kc.pm.org/

**Comment by jhannah** [comment]
@rspier ^ can you add that Apache redirect please?

**Comment by rspier** [comment]
DNS re-added, redirect set up, should take effect soon.

**Comment by rspier** [comment]
Something isn't right, investigating.  @ask Any ideas?

**Comment by djgoku** [comment]
It seems to be working for me. 

Jonathan Otsuka

**Comment by rspier** [comment]
Good!  :)  I'm seeing a bad TLS certificate in the redirect chain.

**Comment by djgoku** [comment]
Is that something I did wrong?

Jonathan Otsuka

**Comment by rspier** [comment]
Actually, this was a mistake on my part.  The version of curl on the box I was testing from doesn't support SNI.

**Comment by rspier** [comment]
No.  It's on our side.  (At least the one I'm noticing.)  Although it might be a problem with how I'm testing with curl and it works fine in the browser.

Yes.  It's my fault, I was using a very old version of curl that doesn't support SNI properly.

**Comment by jhannah** [comment]
Looks like it's working to me.
