### ISSUE TITLE
miltonkeynes.pm.org

### ISSUE THREAD

**Issue by edwart** [perlorg/www.pm.org#129]
Hi
I have just migrated the miltonkeynes pm website to a much cheaper service
Please can you redirect the miltonkeynes.pm.org domain from my old server to the new one at 163.172.162.255
Incidentally, I have the miltonkeynes.pm domain registered and already pointing to this new address

Cheers
Tony
tony@edwardson.co.uk

**Comment by jhannah** [comment]
DNS request submitted. Should take effect in a day or so.

**Comment by jhannah** [comment]
Done.
