### ISSUE TITLE
vienna.pm mailinglist password reset

### ISSUE THREAD

**Issue by domm** [perlorg/www.pm.org#133]
Hi!

I seem to have lost the vienna.pm mailman admin password. But I need it to unsubscribe a few users (at least one of whom has lost access to the email account used to subscribe, so some colleague gets spammed with vienna-pm mail and cannot unsubscribe)

Please advise on how I can reset the password (or send me a new one to domm@cpan.org)

Thanks!
domm

**Comment by jhannah** [comment]
New admin password sent to that email address. Cheers.
