### ISSUE TITLE
Cannot join the yapc@pm.org mailing list.

### ISSUE THREAD

**Issue by toddr** [perlorg/www.pm.org#134]
We're getting:

Bug in Mailman version 2.1.26
We're sorry, we hit a bug!
Please inform the webmaster for this site of this problem. Printing of traceback and other system information has been explicitly inhibited, but the webmaster can find this information in the Mailman error logs.

**Comment by pudge** [comment]
Yes, what @toddr said!

**Comment by jhannah** [comment]
^ @rspier

**Comment by rspier** [comment]
Thanks for reporting this.  I think it's actually been broken for a bit, but no one else has reported it.  Working on fixing it now, it's either going to be straightforward or a huge pain.

**Comment by rspier** [comment]
Should be all fixed now.
