### ISSUE TITLE
yapc@pm.org is down?

### ISSUE THREAD

**Issue by toddr** [perlorg/www.pm.org#137]
Hi, it looks like certain domains are getting filtered so that effectively yapc@pm.org is not working. I currently have the mailing list in emergency moderation so I can see what emails come across and other than my work address, nothing else from gmail or other sources are being delivered to mailman.

**Comment by jhannah** [comment]
^ eep! help @rspier   (sorry I have no adminy access)

**Comment by toddr** [comment]
we are seeing some mail go through now but for sure some are being filtered. @autarch for instance can't seem to mail the list.

**Comment by rspier** [comment]
I'm not sure what's going on with @autarch's mails.  They get almost to mailman and then disappear.

**Comment by rspier** [comment]
If this happens again, please email webmaster at perl.org with details of the lost messages, and we'll investigate.
