### ISSUE TITLE
Mail admin issue, can't discard messages

### ISSUE THREAD

**Issue by coke** [perlorg/www.pm.org#138]
Not sure if this is the right place to ask, but:

Admin for albany@pm.org mailing list, trying to discard spam showing up at https://mail.pm.org/mailman/admindb/albany-pm

but whatever action I try to take, the email isn't processed (screen refreshing, original list of spam still present to act upon)

Any guidance appreciated.

**Comment by jhannah-mm** [comment]
ping @rspier

**Comment by rspier** [comment]
Fixed.

Thanks for reporting.
