### ISSUE TITLE
Madison Perl Mongers still exist

### ISSUE THREAD

**Issue by jimeUWOshkosh** [perlorg/www.pm.org#143]
The Madison Perl Mongers is still going!
https://www.meetup.com/madmongers/

**Comment by jhannah** [comment]
Hi :) Is JT Smith still the leader? https://github.com/perlorg/www.pm.org/blob/master/perl_mongers.xml#L1290-L1296

**Comment by jhannah** [comment]
So if you could update lines 1290-1296 from my link above, or just paste the relevant info here I can update the XML for you and flush the website.

**Comment by jimeUWOshkosh** [comment]
Hopefully I did what was needed.
Thanks for your time!
Have a great day!!!!
