### ISSUE TITLE
 Perl Upgrade with Redhat Linux OS Upgrade

### ISSUE THREAD

**Issue by shijithpkd** [perlorg/www.pm.org#147]
Hello ,
We are using 5.8 version of perl in our organization configured on red-hat linux version 5.X, along with apache, but now the client wants to upgrade perl to latest 5.20 or later verion and also they want to upgrade the Operating system to Redhat linux 7.X. What are all the major changes and key points that must be keep in mind before starting an upgrade. is it advisable to move this much this much lower version to advanced level. Could you please suggest me a solution.

**Comment by jhannah** [comment]
Hi @shijithpkd. This repository is for www.perl.org source code. It's not a Perl support repository. I don't personally know the answers to your questions. Maybe there are links to support resources on http://perl.org? (Mailing lists / IRC / etc.?)
