### ISSUE TITLE
Change DNS for cleveland.pm.org

### ISSUE THREAD

**Issue by StylusEater** [perlorg/www.pm.org#149]
Hello! I'm adjusting the location of cleveland.pm.org to 18.222.83.134. I need DNS updated in pm.org to point to the new location. I submitted a PR for my updated e-mail.

**Comment by jhannah** [comment]
DNS request submitted, should take in a day or so.

**Comment by rspier** [comment]
Done.

$ dig +short cleveland.pm.org
18.222.83.134
