### ISSUE TITLE
Remove me from ownership of London PM lists, possibly remove the lists 

### ISSUE THREAD

**Issue by virtualsue** [perlorg/www.pm.org#150]
I opened a request a few years ago for 2 lists for London PM and the group ended up using Sympa instead. I am no longer associated with London PM.

Very recently I started being alerted about a couple of posts made to the lists in 2015 and 2017. I'd like to be removed from ownership, and possibly the lists themselves should be removed.

**Comment by jhannah** [comment]
I patched our XML file, and changed our MailMan config to Tom's email per the XML file. It appears the mail archive is now empty https://mail.pm.org/pipermail/london-pm/ so ... I guess that solved that problem? I don't know if that was a recent action, or the archive has been offline for a long time or...?
