### ISSUE TITLE
How can PM groups post their upcoming meetings

### ISSUE THREAD

**Issue by matthewpersico** [perlorg/www.pm.org#152]
When PM meetings were local this was not an issue. But now that we're all virutaling, why not post upcoming meetings in one place so we can go "visit" other groups? Can we open up a page (.md) where people could put up their upcoming meetings?

**Comment by matthewpersico** [comment]
Maybe we can use the Wiki for this?

**Comment by jhannah** [comment]
@matthewpersico Me personally, I love wikis. Feel free to use the wiki here for that purpose if you want. :) I know Chicago.pm said they were going to have an online meeting soon, but I couldn't figure out how to keep up to date on when / how / where that was going to be without joining yet another meetup.com (each of which wants to email me 1000 times a day lol).

**Comment by jhannah** [comment]
If you decide to make such a list, here's one for the list: https://www.meetup.com/charlotte-pm/  (I've attended one of them.)

**Comment by matthewpersico** [comment]
http://blogs.perl.org/users/matthew_persico/2020/07/perl-mongers-unite.html

**Comment by matthewpersico** [comment]
@jhannah - sorry it took so long; you wouldn't believe the personal stuff I've had to deal with the past two weeks. Hopefully, this will get the ball rolling.

**Comment by jhannah** [comment]
Looks like a good system to me. :)
