### ISSUE TITLE
June 2020 inactive group cleanup

### ISSUE THREAD

**Issue by jhannah-mm** [perlorg/www.pm.org#153]
Hi! As long-standing policy, any group that appears to be inactive for a year or more is flagged inactive in our XML, removing them from www.pm.org. (I run [bin/deactivate.pl](https://github.com/perlorg/www.pm.org/blob/master/bin/deactivate.pl) which emails the group leader letting them know, so they can update their site if they're still around, or in case we've made a mistake or something.)

Once deactivated, groups can be reactivated by updating their website so they don't look inactive anymore, or by posting to their mailing list (linked from their website), or whatever means of communication they have linked from their website. I apologize in advance for any mistakes I make, and will happily reverse them.

If you have a few minutes, could you look at the 3-5 groups geographically closest to you? If they're inactive, can you please comment this ticket telling me the group name and I'll add them to the deactivation run list? Thanks for helping us keep our list of groups up to date! <3

**Comment by jhannah-mm** [comment]
Known list so far:
```
Swindon.pm - http://swindon.pm.org/ is 404
```

**Comment by jhannah** [comment]
I manually sent an email to all the tsars listed above.
