### ISSUE TITLE
shibuya.pm.org DNS change

### ISSUE THREAD

**Issue by miyagawa** [perlorg/www.pm.org#154]
Hi,

The server that's hosting shibuya.pm.org website is going EOL and i'm moving the site to a static hosting on GitHub Pages at https://github.com/miyagawa/shibuya.pm.org/ 

Please update the DNS entry for `shibuya.pm.org` to `CNAME miyagawa.github.io`

Thank you!

**Comment by jhannah** [comment]
DNS request submitted. Sorry for the delay. It should take effect in a day or so. Thanks.

**Comment by miyagawa** [comment]
Looks like the change is live. Thanks!
