### ISSUE TITLE
shibuya.pm.org DNS update

### ISSUE THREAD

**Issue by miyagawa** [perlorg/www.pm.org#155]
Hi, in #154 I requested to update shibuya.pm.org to a CNAME record, but i forgot that we had previously setup MX records for it using G Suite as well. Because you can't have both CNAME and MX on the same record, MX records are now removed. I'd like it to be A records instead.

Here's the list of A records (via https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

and MX records:
```
1	ASPMX.L.GOOGLE.COM.
5	ALT1.ASPMX.L.GOOGLE.COM.
5	ALT2.ASPMX.L.GOOGLE.COM.
10	ALT3.ASPMX.L.GOOGLE.COM.
10	ALT4.ASPMX.L.GOOGLE.COM.
```

**Comment by jhannah-mm** [comment]
DNS request `[perl #134742]` created. Should take effect in a day or so.

**Comment by rspier** [comment]
If you want this DNS config, I'd appreciate if you (@miyagawa ) would setup an intermediate host we can CNAME.  We're trying to simplify our config, and not manually maintain multiple records for groups.

(At one point, years ago, I had a volunteer who was going to let us autogenerate the DNS from the master groups file, but they never finished the project.)

**Comment by miyagawa** [comment]
@rspier that's exactly what i requested in #154 and how it's done now, but unfortunately, DNS doesn't allow you to have both MX and CNAME on the same record :/

**Comment by miyagawa** [comment]
I guess alternatively I can setup a new zone for shibuya.pm.org on my DNS servers (linode) and you can add NS record on shibuya.pm.org, i think? Does that work for you?

**Comment by rspier** [comment]
Can you setup 

shibuya.somedomain.com
A ...
MX ...

and then we can

shibuya.pm.org CNAME shibuya.somedomain.com

-R

**Comment by miyagawa** [comment]
OK, i just added `shibuyapm.bulknews.net` for it.

**Comment by rspier** [comment]
Master server updated.  May take a little to propagate.

**Comment by miyagawa** [comment]
working for me locally. Thanks!
