### ISSUE TITLE
I'd like to take over the Seattle chapter of Perl Mongers

### ISSUE THREAD

**Issue by chardin** [perlorg/www.pm.org#156]
Hi, I'm Chuck Hardin.  I used to run Thousand Oaks Perl Mongers, and have given talks at Boston, LA, and Orange County Perl Mongers.  I've moved to Redmond now, and I'd like to keep promoting Perl here.

I tried to contact Andrew Sweger, the current Tsar of record for Seattle Perl Mongers, but the email bounced.  I did a quick search, and was saddened to see that [he died in 2019](https://www.dignitymemorial.com/obituaries/bellevue-wa/andrew-sweger-8756577).

I'd like to take over the group.  I tried to generate a pull request on a fork of perl-mongers.xml, as suggested in [the relevant FAQ](https://www.pm.org/faq/hosting.html#new), but got an error:

`remote: Permission to perlorg/www.pm.org.git denied to chardin`

I'm not sure how to proceed.  How do we do this?

**Comment by jhannah-mm** [comment]
Hey @chardin you can fork the repo in github and post a pull request against upstream (this repo). Or just post your diff and I'll apply it for you. Thanks!

**Comment by chardin** [comment]
I guess I was unclear before.

I checked out the git repo, created a topic branch for this change, and tried to push that topic branch to the repo.  This is how I have forked repos before, and created branches against which I can make pull requests to master.  Pushing my topic branch failed with the error I mentioned.

Is there some other way to implement your suggestion, and if so, what is it?

I'll want to be able to do this in future, so I'd like to get this working.

I have some other questions as well.  There's an existing mailing list for SPUG, and I'd like to be able to use it to contact the members.  Is that hosted by Perl Mongers, and if so, what do I need to do to administer it?

I'm guessing that there's no way for me to get seattleperl.org, since Perl Mongers doesn't host PM chapter websites any more.

**Comment by jhannah-mm** [comment]
Hi @chardin, I think what you did was `clone` the `perlorg/www.pm.org` repo to your local computer. That doesn't give you any permissions to push your branches to this repo.
What I'm suggesting you do instead is use a github feature called `Fork` (there's a `Fork` button in the upper right of github.com). When you `Fork` this repo github will create another repo `chardin/www.pm.org` which you have full administrative permissions to. You can then push your branches / changes (do anything you want) to that repo. You own it. You can also then open a Pull Request asking `perlorg/www.pm.org` to merge a branch you've written in your `chardin/www.pm.org` repository. Which we will happily and gratefully merge into this repo. This probably sounds like a lot of work, but `Fork` is a pretty slick feature for lots of repos. Once you've done it once it's pretty easy. :) (Again, if this is a pain, you can just paste the info to me and I'll do it.)

We host this mailing list, yes: https://mail.pm.org/mailman/listinfo/spug-list You'll become the admin of that once I have your full name / email address etc from your PR.

We have no control over seattleperl.org, no.

**Comment by chardin** [comment]
Thank you, that is quite clear!

I have created a pull request at https://github.com/chardin/www.pm.org/pull/1 for your review.

**Comment by chardin** [comment]
Is there something wrong with my pull request?  It's been over a week and it appears to be unmerged.  Is there something else I need to do?

**Comment by jhannah** [comment]
@chardin nope, sorry, my hobby laptop died. Rigging my work laptop up for also doing my hobby github stuff.

**Comment by jhannah** [comment]
* www.pm.org flushed
* Mailing list admin password changed, I emailed you your new password (please change it)
* I added you to the group leader mailing list
* Let us know where you want your DNS pointed for your web site.

**Comment by chardin** [comment]
I think I gave a link to the webpage I want to use.  It was in the XML, and https://www.pm.org/groups/95.html seems to have a pointer to it.  Or do you want something else?

Everything else seems to be working.  I did change the password.

**Comment by jhannah** [comment]
Ah, gotcha cool. 👍 
Can you please put a date stamp on https://www.naming-schemes.org/seattle.pm/ ? If the website is still blank in a year I'll deactivate your group. ( We don't want a bunch of zombie groups in our active group list. :) ) Thanks!

**Comment by chardin** [comment]
It is date stamped.  And I won't need a year to do the right thing.

Thank you very much!

**Comment by jhannah-mm** [comment]
> I will bite off and eat my left little finger.
lol thanks!
