### ISSUE TITLE
Houston.pm: How to transfer group leadership

### ISSUE THREAD

**Issue by gwadej** [perlorg/www.pm.org#157]
I've been the leader for Houston.pm for a while now, and I've found someone who is willing to take over leadership.

How do I get the leadership changed?
How does he get the DNS updated to his hosting service when he is ready?

G. Wade Johnson

**Comment by jhannah-mm** [comment]
You can patch [perl_mongers.xml](/perlorg/www.pm.org/blob/master/perl_mongers.xml) by creating a pull request or telling me what the changes are and I'll do it.
You can tell me here what the new DNS info is and I'll create the DNS change request.
https://www.pm.org/faq/hosting.html#new
Cheers

**Comment by jlbprof** [comment]
JHannah-mm

I am Julian Brown, and I will be taking over.  I am hoping to have hosting in a day or so, and can get you an IP soon.

Thank you

Julian Brown

**Comment by jhannah** [comment]
Hi @jlbprof I'm modding the XML file anyway today so if you want to just tell me here what the new info is I can make the change for you...

    <tsar>
      <name>G. Wade Johnson</name>
      <email type="personal">
        <user>gwadej</user>
        <domain>anomaly.org</domain>
      </email>
    </tsar>

**Comment by jhannah** [comment]
Oh, nevermind, looks like #158 does it, merging / fliushing website. :)

**Comment by jlbprof** [comment]
<tsar>
  <name>Julian Brown</name>
  <email type="personal">
    <user>julian</user>
    <domain>j <http://anomaly.org/>lbprof.com</domain>
  </email>
</tsar>


Thank you
