### ISSUE TITLE
Houston.pm.org - new IP address

### ISSUE THREAD

**Issue by jlbprof** [perlorg/www.pm.org#159]
This is a follow up for the Transfer of Houston.pm leadership to me, Julian Brown.

I have a new IP address to have it send to.

184.94.207.74

Currently it is just proxying to the old site, while we build the current one.

Thank you for your considerations.

Julian Brown

**Comment by jhannah-mm** [comment]
DNS request # 134821 created. It should take effect in a day or so.

**Comment by jlbprof** [comment]
Thank you
