### ISSUE TITLE
Consolidate Australian PM's in to one

### ISSUE THREAD

**Issue by djzort** [perlorg/www.pm.org#161]
There is a consensus on the sydney, melbourne, and brisbane PM lists to consolidate PM's in to one nation wide Australia PM group.

I cant link those threads as the email lists archives are private.

I dont know if this is the right place to kick off that process. Hopefully it is.

**Comment by jhannah** [comment]
huh. So in my mind, the point of geographically distint groups is that if I'm visiting Melbourne I may want to see what's going on in Melbourne. If the answer is "there's a meeting on Tuesday in Sydney" umm... That seems unhelpful? If some of those cities no longer have an active local group we should suspend those groups?

**Comment by jhannah** [comment]
By which I don't intend to discourage activities around "Austrailian Perl" -- that's great! I just don't think that's how pm.org hosted services should be organized to be the most useful.

https://www.pm.org/faq/hosting.html#new
> 99% of the time your group name will be the name of the city in which your meetings will typically be held. So, since I live in Omaha my group name is Omaha.pm.

Perhaps I'm wrong or my thinking is outdated. But in the past when we had umbrella groups, individual (smaller) groups hosting in individual cities would rightfully (in my opinion) complain about being overshadowed by umbrella groups.

None of this stops sydney, melbourne, and brisbane all redirecting to the same "Australian Perl" website, mailing list, etc., because they choose to.

**Comment by djzort** [comment]
I emailed all the active email lists proposing to consolidate the email lists, social media etc so there is just one Australia wide PM. With the minimal local meet up activity being organized through that single point. There is however, nothing consistent going on, just the odd person in visiting a given town looking to have a social drink or something. 

The advantage of an australia PM is we could more easily begin doing virtual PM events, which many people expressed interest in. Even when i was running regular Sydney PM events in the recent past, the geography of Sydney left many people feeling the travel was too great a burden.

Alas i cant link the email responses in the syd, bris, and mel lists.

**Comment by jhannah** [comment]
Understood. We host the XML file that drives the map and list of pm.org (you can pull request `/perl_mongers.xml` or I can do that for you). We do DNS, and Mailman lists. What list of things would you like me to change?

**Comment by djzort** [comment]
Phase 1 is to create an australia@pm.org list and to copy all the registrations from the other lists in to it. Then retire the old lists.

I can then send you a PR against perl_mongers.xml

**Comment by jhannah** [comment]
@djzort you should have received email about the new list. You're the owner. Admin: https://mail.pm.org/mailman/admin/australia-pm pw `oyoyoy`. Please change the password. I'm not comfortable mass-adding anyone, feel free to do so, or tell people to self-serve to do that. We don't retire old lists, they (the archives) just sit "forever." Let me know what else I can do for you.
