### ISSUE TITLE
All checked *.pm.org not available

### ISSUE THREAD

**Issue by skupkosk** [perlorg/www.pm.org#163]
Some of the DNS records seems to be not resolvable.

Found:
- bratislava.pm.org
- bergen.pm.org
- porto.pm.org

**Comment by jhannah** [comment]
Thanks for the report! I emailed the group leaders know their groups have been inactivated for now.

**Comment by christopherraa** [comment]
Speaking for Bergen PM: I don't think we've ever used that domain. https://bergenpm.org has been up forever and is really the only site we've concerned ourselves with. ....aand that might explain by nothing on bergen.pm.org is responding.

**Comment by jhannah** [comment]
@christopherraa oh cool! Thanks! Re-activating w/ updated URL

**Comment by jozef** [comment]
Bratislava PM group is inactive
