### ISSUE TITLE
remove nl.pm.org

### ISSUE THREAD

**Issue by jpcornet** [perlorg/www.pm.org#168]
Hi pm.org maintainers,

A long long time ago, in a century where manual custom settings were easy to apply, Amsterdam.pm.org also got the regional access name "nl.pm.org". That is currently still delegated to the xs4all nameservers, but xs4all is going bye bye, and it's better to adhere to the standard $CITYNAME.pm.org, so can you please remove the nl.pm.org zone? I've already marked it as "discontinued" in the current DNS.

Thanks!

**Comment by jhannah-mm** [comment]
DNS request 135269 submitted. Should take effect in a day or so.

**Comment by jhannah** [comment]
✗ host nl.pm.org
    Host nl.pm.org not found: 3(NXDOMAIN)
