### ISSUE TITLE
hyderabad.pm.org

### ISSUE THREAD

**Issue by kancherlanagaraju** [perlorg/www.pm.org#174]
https://www.pm.org/groups/236.html

Looks like most of the groups are down.
I have noticed my group site is not up. Seems like it was attacked and was down.
Appreciate if you could bring this site back.

https://www.pm.org/groups/236.html

I can be reached at hyderabad.pm@gmail.com

thanks,
Raj

**Comment by jhannah** [comment]
Where are you hosting your website? Your DNS doesn't exist, we can point it to wherever you're hosting?

    ✗ host hyderabad.pm.org
    Host hyderabad.pm.org not found: 3(NXDOMAIN)

**Comment by jhannah** [comment]
Since I didn't hear back, I deactivated this group for now.
