### ISSUE TITLE
rt.perl.org Auth0 is down?

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#175]
@rspier from https://rt.perl.org/ when I click "Sign in with Auth0" I immediately end up here?

https://rt.perl.org/NoAuth/OAuthRedirect?code=HMIQ2dEC-5u6vPsW2TVungK9caZH-KnymacP6bL-IcXMj&state=%2F
An internal RT error has occurred. Your administrator can find more details in RT's log files.

**Comment by rspier** [comment]
Acknowledged.  I need to figure out the best way to fix this.  There are a few options, and none of them are easy.

**Comment by jhannah** [comment]
Awesome, thank you @rspier. FYI, also for #176 I sent an email to dns@perl.org and haven't received an auto-reply w/ ticket number from RT, so maybe the email interface is also struggling to open new tickets. Thank you for all you do!! <3

**Comment by rspier** [comment]
Auth0 fixed.  It wasn't as bad as I feared, just hacky.

**Comment by rspier** [comment]
(And to be clear: This wasn't Auth0's fault.)
