### ISSUE TITLE
SanDiego.pm.org DNS update

### ISSUE THREAD

**Issue by rkleemann** [perlorg/www.pm.org#176]
A comment from LAMP Host, which hosts our machine:

> We are doing a network update and need to have the "A" record for "sandiego.pm.org" changed from "69.43.195.46" to "69.55.235.46". Can you please work with pm.org to have this change made?

Please let me know what else I need to do to make this happen, or when this is accomplished.

**Comment by jhannah** [comment]
I fired off the request, which historically takes ~1 day to take effect. Currently, though, we may be having RT problems (#175) so it may take longer? I usually get an auto-response from RT, which hasn't arrived back to me yet...

**Comment by jhannah** [comment]
Looks like it's working as of yesterday.

    ✗ host sandiego.pm.org
    sandiego.pm.org has address 69.55.235.46
