### ISSUE TITLE
Trying to contact a perl group in America 

### ISSUE THREAD

**Issue by chalan51** [perlorg/www.pm.org#177]
Hello there!
When I try to open the link to the xxx.pm.org where xxx may be santiago, lima or any other i get an error: "No podemos conectarnos al servidor en lima.pm.org." (we can not connect to the server lima.pm.org).
What am I doing wrong?
Thanks in advance for your answer/orientation!
Juan Manuel Carrillo Campos
juanm_c@hotmail.com

**Comment by jhannah-mm** [comment]
I cc'd you on an email I sent the group leader. I'm guessing the group went inactive so the DNS was deactivated because it was broken?
