### ISSUE TITLE
Fuzhou.pm follow-up

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#183]
Hi @zcns this issue is so I can follow up on these:
* https://www.pm.org/groups/792.html is as good as it can be, so far. :)
* We need an email address for the group leader (you).
* DNS request 135484 should take effect in a day or two.
* Please get a basic website set up.

**Comment by zcns** [comment]
Sorry, please replace (Fuzhou, Fujian Fuzhou, China, Asia) with (Fuzhou, China, Asia)

**Comment by zcns** [comment]
My email is bnmlaw@foxmail.com

**Comment by zcns** [comment]
I have set up the website at [cnorgs](https://github.com/cnorgs/cnorgs.github.io).

**Comment by jhannah** [comment]
Huh. Something went wrong with the DNS request. New request 135497 submitted.
I updated your email address.
Can you please add basic contact information to your website? Thanks. :)

**Comment by jhannah** [comment]
@rspier Can you help here? I've submitted 2 DNS requests (135484, 135497) but there's still no DNS entry?

**Comment by rspier** [comment]
Done.  Sorry for the delay.

**Comment by jhannah** [comment]
@zcns looks like DNS is working, but you need to set this up as a custom domain in Github Pages?
```
host Fuzhou.pm.org
Fuzhou.pm.org is an alias for cnorgs.github.io.
cnorgs.github.io has address 185.199.108.153
cnorgs.github.io has address 185.199.111.153
cnorgs.github.io has address 185.199.110.153
cnorgs.github.io has address 185.199.109.153
```

**Comment by jhannah** [comment]
Looks like @zcns never got a website set up? So I de-activated the group. Please let us know when you've got a website up and we can re-activate.
