### ISSUE TITLE
Copenhagen.pm seems to be dead

### ISSUE THREAD

**Issue by rol1** [perlorg/www.pm.org#184]
Mail can't be delivered:
_This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of
its recipients. This is a permanent error.

The following address failed:

    contact@copenhagen.pm.org:
        multiple delivery attempts failed_

Webseite http://copenhagen.pm.org/ unavailabe:

_No website is currently present on this hostname_

**Comment by jhannah** [comment]
Thanks!

**Comment by sjn** [comment]
It seems there's been some activity on the list lately, btw. 🙂

**Comment by jhannah** [comment]
Hmm...
* The website is 404 http://copenhagen.pm.org
* I don't see a MailMan for them? https://mail.pm.org/mailman/listinfo/ What list are you talking about?

**Comment by sjn** [comment]
Ah. The list I'm subscribed to is copenhagen@perl.org. Don't know about the website.

**Comment by jhannah** [comment]
> Ah. The list I'm subscribed to is [copenhagen@perl.org](mailto:copenhagen@perl.org). Don't know about the website.

Fascinating. I don't know who / how they admin that mailing list. If you're subscribed could you drop them a note asking if someone could take a look into their website and volunteer as group leader so pm.org can re-activate them? Thanks!
