### ISSUE TITLE
Houston.pm.org changing ip

### ISSUE THREAD

**Issue by jlbprof** [perlorg/www.pm.org#186]
I read your FAQ and you are only able to provide a 301 redirect.

Please redirect houston.pm.org to 

192.46.219.109

Our machine died a couple of weeks ago, and this is the new IP address.

Thank you

Julian Brown
Head guy at Houston Perl Mongers

**Comment by jlbprof** [comment]
It might make better sense to redirect to our new domain: houstonperlmongers.org

**Comment by jhannah** [comment]
Ooof, sorry I didn't notice this for 3 months!! :(
So, per Slack, what we want is:
```
Houston.pm.org A 192.46.219.109
```
So I fired that off to the DNS queue in RT, but I didn't get the auto-responder... Is that RT functionality broken?
@rspier hepl!? <3

**Comment by jhannah** [comment]
Per Slack, it's working now 👍
