### ISSUE TITLE
ny.pm.org: Can't subscribe or unsubscribe

### ISSUE THREAD

**Issue by jkeenan** [perlorg/www.pm.org#187]
Within the last week a long-time (25-year-+) member of New York Perlmongers wrote to me requesting that the email address at which he was subscribed to the ny.pm mailing list be changed.  I responded that I had no special access to that list (I only have access to our meetup.com page), so I started to write a response to him to advise him to follow the instructions for subscribing and unsubscribing to the list.

But, I thought, maybe I should make sure that those instructions are still valid.  As best as I can determine, those instructions were:
```
**To Subscribe, send "subscribe ny" to majordomo@lists.pm.org**
**To Unsubscribe, send "unsubscribe ny" to majordomo@lists.pm.org**
```
I know that those instructions were valid as of April 9 2023 because I practiced subbing and unsubbing on that day and a new member was able to join following those instructions.

So about 3 days ago, I sent "subscribe ny" messages from two different email addresses.  I never got the expected confirmation request message back from either account.  So that leads me to suspect that the majordomo application is broken, at least for ny.pm and probably also for any other chapters using it.

Can you investigate?

Thank you very much.

**Comment by jhannah** [comment]
Oh, wow, I didn't think this was possible, but the NYC mailing list predates even me! ;) For decades we've been using Mailman for all our PM mailing lists, but NYC isn't in Mailman anywhere as far as I can tell: https://mail.pm.org/mailman/listinfo

Did NYC, decades ago, somehow escape the move to Mailman?

And I don't see NYC in https://lists.perl.org/all.html#n either...

So your `lists.pm.org` seems to be outside of everything I'm aware of (`mail.pm.org`, `lists.perl.org`)... maybe @rspier knows?

**Comment by jkeenan** [comment]
Well, it's quite possible that, as the *first* Perlmongers chapter, back in the day the Founders made their own arrangements.  I guess we'll have to follow up with Panix.  I'll update this ticket when I have more info.  Thanks!

**Comment by rspier** [comment]
ny.pm never migrated, because Panix was working great for them.  Other early groups used Panix too for a while, but I don't think anyone but ny has for over a decade.

**Comment by jhannah** [comment]
Ahh, excellent. Mystery solved then. :) Thanks! Closing ticket since there's nothing PM support can do about a 3rd party (Panix) Majordomo install.

**Comment by matthewpersico** [comment]
“The Founders”. Sounds like the first page of a sci-fi story.

Matthew O. Persico

**Comment by rspier** [comment]
The Founders are from Star Trek: https://memory-alpha.fandom.com/wiki/Founder

ny.pm was definitely a Dr. Who leaning organization.

**Comment by briandfoy** [comment]
The Founder here. There's nothing for NOC to do here.

I think everything was set up in my personal account at PANIX. This was before pm.org was a thing maybe. We never relied on any central services and for the first several years I actively discouraged providing central services because of the burden of volunteer effort. All the eventually failed.

FWIW, most of the original ny.pm plank holders were PANIX customers. I think Alexis Rosen might have been the one to donate services, and if you run into trouble he can probably help.
