### ISSUE TITLE
Omaha-pm Mailman archive

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#188]
Hi @rspier! To my surprise someone was reminiscing about Omaha Perl Mongers 2010 and I was delighted to see the archives still online <3

   https://mail.pm.org/pipermail/omaha-pm/
   
Now and/or if there's any thought of purging old archives can I get an Omaha snapshot (tarball / whatever) before it goes poof forever? I could web-scrape it down, but presumably that would be silly of me. :) Thanks!

**Comment by rspier** [comment]
Emailed you off-bug.

**Comment by jhannah** [comment]
ha neat, mhonarc still works.
http://jays.net/archives/2004-2016-omaha-perl-mongers/
