### ISSUE TITLE
Birmingham.pm Server Move

### ISSUE THREAD

**Issue by barbie** [perlorg/www.pm.org#189]
Hi Ask & Robert,

Birmingham Perl Mongers have moved their server. Please could you update the IP attached to birmingham.pm.org to 154.56.56.8.

Many thanks,
Barbie.

**Comment by jhannah** [comment]
DNS request 135632 created, should activate in a day or so. Thanks!

**Comment by jhannah** [comment]
Looks like that DNS change is in effect on the inter-tubes
