### ISSUE TITLE
Please HTTP-redirect athens.pm.org to https://athens.perl.gr

### ISSUE THREAD

**Issue by akarelas** [perlorg/www.pm.org#191]
As it says here: https://www.pm.org/faq/hosting_faq.html#dns

**Comment by jhannah** [comment]
🤔 ... I think our Apache redirect mechanism was deprecated with WebDAV like 10 years ago... I've forgotten... looking... maybe @rspier remembers either way...

**Comment by rspier** [comment]
Also, athens.perl.org is not a valid hostname.

**Comment by akarelas** [comment]
You're right, sorry, I was mistaken. The correct hostname is: athens.perl.gr

**Comment by jhannah** [comment]
@rspier -blink- Sorry, I'm confused. https://www.pm.org/faq/hosting.html#dns

>  We no longer provide A or CNAME records. We will happily provide you with a HTTP 301 redirect to your website.

I thought we *only* did A, CNAME (and newer fancier versions thereof for GitHub Pages / Netlify / whatever)? Apparently we're doing DNS via bitnames.com nowadays? Do we offer HTTP 301 redirects? If so, how do you want me to ask for those?

```
$ dig +trace berlin.pm.org
pm.org.			3600	IN	NS	ns1.eu.bitnames.com.
;; Received 657 bytes from 199.249.120.1#53(b2.org.afilias-nst.org) in 51 ms

berlin.pm.org.		7200	IN	CNAME	berlinpm.github.io.
;; Received 74 bytes from 68.183.187.150#53(ns3.us.bitnames.com) in 304 ms
```

**Comment by akarelas** [comment]
I prefer an A record, but if I can't have, then I'd like a HTTP redirect.

**Comment by jhannah** [comment]
DNS request 135665 submitted. It should take effect in a day or so.

(He said, still confused about our docs.😉)

**Comment by akarelas** [comment]
@jhannah  2.5 days later the A record hasn't appeared

**Comment by jhannah** [comment]
@akarelas confirmed. I don't have direct access to fix that, your request is in queue. We're all volunteers, so sometimes things take a while. Apologies.

**Comment by akarelas** [comment]
CNAME added. Thanks!!!!!
