### ISSUE TITLE
Inconsistency in documentation: You point *.pm.org DNS records vs You don't (in another part of the documentation)

### ISSUE THREAD

**Issue by akarelas** [perlorg/www.pm.org#192]
Here it says you do: https://www.pm.org/faq/hosting_faq.html#dns

Here it says you don't: https://www.pm.org/faq/hosting.html#dns

On one, you also say you do MX records, and on the other that you don't.

**Comment by jhannah** [comment]
Ah, I've been failing to update the docs forever. Thanks for prompting me to cleanse them... /me dives in

**Comment by jhannah** [comment]
Looks like `hosting_faq.html` is an old filename that wasn't purged from the github repo that publishes the live site. It doesn't exist (anymore) in the source code github repo (here). Those are two separate repos for... ease of deployment reasons? One is in github, one isn't. Updating the docs to explain all this.

**Comment by jhannah** [comment]
Copy/pasting this from #191 since that one's closed now:

@rspier -blink- Sorry, I'm confused. https://www.pm.org/faq/hosting.html#dns

>  We no longer provide A or CNAME records. We will happily provide you with a HTTP 301 redirect to your website.

https://github.com/perlorg/www.pm.org/commit/d1fa8e553deb868fc6e491f8ea627f2fdea4a9a0#diff-0303954f835f84bc090f3ecafa99110bf684d31d69940cbe717c506e06059435R52

I thought we *only* did A, CNAME (and newer fancier versions thereof for GitHub Pages / Netlify / whatever)? Apparently we're doing DNS via bitnames.com nowadays? Do we offer HTTP 301 redirects? If so, how do you want me to ask for those?

```
$ dig +trace berlin.pm.org
pm.org.			3600	IN	NS	ns1.eu.bitnames.com.
;; Received 657 bytes from 199.249.120.1#53(b2.org.afilias-nst.org) in 51 ms

berlin.pm.org.		7200	IN	CNAME	berlinpm.github.io.
;; Received 74 bytes from 68.183.187.150#53(ns3.us.bitnames.com) in 304 ms
```

**Comment by rspier** [comment]
I think we're going to standardize on only offering redirects.  There may be some limited cases (like legacy sites with useful content ( e.g. #196 )) where we'll still do an A or CNAME, but expect them to be rare.  

I have a plan for how to simplify/automate the redirect setup significantly.

**Comment by rspier** [comment]
I have a prototype running that serves redirects 100% based on the `perl_mongers.xml` file.  If the <web>` element points away from `pm.org` it redirects.  Otherwise it returns an error.  It makes setting up a redirect site 1 commit.

**Comment by rspier** [comment]
We do not provide DNS to new groups.  For existing active groups in good standing, we will continue to provide legacy DNS services.

**Comment by rspier** [comment]
@jhannah If you put the redirect target as the `<web>` field in the xml file, magic happens.

**Comment by akarelas** [comment]
> We do not provide DNS to new groups. For existing active groups in good standing, we will continue to provide legacy DNS services.

athens.pm.org now resolves differently than before for some reason, and points to a page that only says "Gone"

**Comment by akarelas** [comment]
I mean, its DNS changed just now.

**Comment by rspier** [comment]
Please create new issues for individual groups.  The Athens perl monger site appeared moribund.  There was no evidence it is still a functioning group.

**Comment by akarelas** [comment]
@rspier Okay thanks. I wrote more here: https://github.com/perlorg/www.pm.org/issues/197 - Please someone read.
