### ISSUE TITLE
Policy for sites in "archive" mode?

### ISSUE THREAD

**Issue by grantm** [perlorg/www.pm.org#196]
I notice that a recent commit (ddae9c50) marked wellington.pm as inactive - which is fair since the group merged with other local Open Source groups in 2018. However the web site was deliberately kept online with an archive of past talks (including slides) and events. In particular the site has had a steady trickle of visitors solving the programming problems from our [hackoff events](https://web.archive.org/web/20210518081357/https://wellington.pm.org/articles/hackoff2010/). Now that the DNS has disappeared our site has dropped off the internet.

I see in the FAQ that you no longer offer CNAME records but there still seem to be some active ones.  If it were an option, I'd really appreciate an CNAME pointing to `apps.mclean.net.nz`, but failing that a 301 to `https://www.mclean.net.nz/wellington-pm-archive/ ` would be better than nothing.

Regards
Grant

**Comment by jhannah** [comment]
Regardless of the not-yet-resolved confusion in our docs (#192), we apparently still do CNAMEs, we did another one last week.

I have no problem at all with you hosting a virtual website for wellington.pm.org that says "Hey, thanks for your interest in Perl Mongers! We're still active, but in 2018 we merged with [link to other meetup website(s)], please click that link and join us at those meetings!" (I did this for Omaha.pm for years, it was fine, imo.)

If that website existed, and the other site(s) looked active, then that Perl Mongers group in `active` as far as I'm concerned. 🙂 Is that fair? Could you update your "archive" site to say that? If so, we can re-active and add:

    wellington.pm.org CNAME apps.mclean.net.nz

**Comment by grantm** [comment]
Many thanks Jay

I've updated the site as you suggest.

Regards
Grant

**Comment by jhannah** [comment]
DNS request # 135670 submitted. Should take in a day or so. Thanks!
