### ISSUE TITLE
https://athens.pm.org points to a page that just displays "Gone" (not belonging to me)

### ISSUE THREAD

**Issue by akarelas** [perlorg/www.pm.org#197]
It used to work until a few hours ago, and its DNS pointed to athens.perl.gr IIRC.

PS I'm the supreme leader of Athens PM.

**Comment by akarelas** [comment]
Our PM group had just woken (last month) from the dead after so many years, and I was preparing to revive it by actively promoting it to greek Perl users. Our mailing list has 15 users (most registered from 2010-2018) and our IRC channel (athens-pm on libera.chat) acquired 2 permanent (foreign) members who found about the channel from our athens.pm.org site, and who came into the channel to meet greeks when they visit Greece for vacations. And we have an excellent chatbot in our channel, with AI who can write Perl scripts very quickly. And I've already arranged to meet one of them together with a greek user who knows Perl.

If you do not re-instate our website to athens.pm.org, then I won't have a site to show to attract Greeks.

What is the requirement to reinstate the DNS or an HTTP Redirect to our website? Is it to have 2 active members from Athens? If that's it, it's okay, please tell me and I'll let you know when I get the second member. If it's to have 1 active member, we've already got that (me).

Awaiting your response,

Thanks,

- akarelas

**Comment by rspier** [comment]
athens.perl.gr looks like:

![image](https://github.com/user-attachments/assets/3150b0db-cc3a-4960-a1cf-f404b6e1513b)

**Comment by akarelas** [comment]
@rspier Fixed.

**Comment by akarelas** [comment]
@rspier Fixed.

**Comment by akarelas** [comment]
![image](https://github.com/user-attachments/assets/14de4642-8c6f-48ee-8614-a2da338e2b18)

**Comment by akarelas** [comment]
I had disabled it, since athens.pm.org was the host. But now it's re-enabled.

**Comment by rspier** [comment]
In about 15 minutes, Athens.pm.org should redirect to Athens.perl.gr.  I'd encourage you to make the website a little more contentful, and update it periodically so that the group appears active.
