### ISSUE TITLE
XML -> DNS

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#36]
Our goal is to automatically generate `/dns.txt` (DNS) from `/perl_mongers.xml` (XML).

But XML does not yet have any DNS info in it. So we need to write a temporary script to put DNS into XML once. When completed, discard that script.

Then we need a script which generates DNS from XML. 

When complete, automation will be added to send that DNS file to the DNS server(s) automatically.

**Comment by rspier** [comment]
FYI, Tom Metro is working on this.

**Comment by jhannah-mm** [comment]
@rspier if this is something we still want, I can take this on. Is the above information still accurate of what you would use in 2020? Is there a current DNS list that I can put INTO the XML so we could, thereafter, pull the DNS list FROM the XML?

**Comment by rspier** [comment]
Hi Jay,
  I'll email you off-bug to to discuss more.
-R
