### ISSUE TITLE
Capetown.pm broken?

### ISSUE THREAD

**Issue by jhannah** [perlorg/www.pm.org#44]
Hi @nkukard. It appears #42 isn't working? Your domain isn't responding?

    ✗ ping capetown.pm
    PING capetown.pm (197.85.190.65): 56 data bytes
    Request timeout for icmp_seq 0
    Request timeout for icmp_seq 1

Thanks!

**Comment by nkukard** [comment]
maintenance on the hosting platform for 4 hours last night
http://www.isitdownrightnow.com/capetown.pm.html

**Comment by jhannah** [comment]
Thanks!
