### ISSUE TITLE
Old Email address

### ISSUE THREAD

**Issue by edwart** [perlorg/www.pm.org#47]
Hi

I notice that my contact details for Milton Keynes Perl Mongers is no longer correct.
Please can it be corrected from Tony.Edwardson@usa.net to tony@edwardson.co.uk
on page http://www.pm.org/groups/675.html

Thanks
Tony

**Comment by davorg** [comment]
Hi Tony,

This stuff now works on pull requests. Can you fork the repo (https://github.com/perlorg/www.pm.org), make your changes and then send a pull request.

Cheers,

Dave...

**Comment by edwart** [comment]
OK Ta - wil do that
