### ISSUE TITLE
gainesville.pm dormant since 2004

### ISSUE THREAD

**Issue by lindleyw** [perlorg/www.pm.org#49]
https://web.archive.org/web/20041130094729/http://gainesville.pm.org/

shows the "Oct. 12" meeting which is still listed at http://gainesville.pm.org/ was actually in 2004.

Can this page be at least updated so no-one tries to show up decades late?

Is anyone still alive in gainesville.pm ?

**Comment by jhannah** [comment]
Thanks! :)
