### ISSUE TITLE
update A record for dfw.pm.org

### ISSUE THREAD

**Issue by tommybutler** [perlorg/www.pm.org#50]
We need someone to update the A record for dfw.pm.org to point to 209.59.138.232

We would also like our meetings to show up on your calendar of events at pm.org.  We meet the 2nd Monday of each month.

Thank you,
Tommy Butler, DFW.pm President.

**Comment by jhannah** [comment]
Hi Tommy, I submitted your DNS request (#124037). Should take effect in a day or so. 

Not sure who manages the "Worldwide Perl Conferences" calendar that's embedded on pm.org. I assume it's just for conferences? Looks like @szabgab is the guy to talk to? 1fcdd13e2

**Comment by jhannah** [comment]
Looks like your new DNS is working. Cheers!

**Comment by tommybutler** [comment]
Thank you,  Jay :-)

-- 
Tommy Butler
