### ISSUE TITLE
Change of DNS for bergen.pm.org

### ISSUE THREAD

**Issue by christopherraa** [perlorg/www.pm.org#51]
Hi,

Could you please change the CNAME for bergen.pm.org from 'bergenpm.github.io' to 'bergenpm.org'? These are all domains controlled by @BergenPM , managed by me and two others.

Do you need any other verification before making this change?

Best,
Christopher

**Comment by jhannah** [comment]
DNS request submitted (124100). It should take in a day or so. :)

**Comment by christopherraa** [comment]
Excellent. Thank you for your assistance. I'll close this issue for now as I see no reason why the change should not take. Have a great day.

**Comment by jhannah** [comment]
sometimes requests get missed / typo'd -- so I usually leave requests open until the fix is verified. :) With this closed I doubt I'll remember to check.
