### ISSUE TITLE
installing WIN32::SerialPort on W7 failing

### ISSUE THREAD

**Issue by gnuperl** [perlorg/www.pm.org#52]
Hello, 
I am new to perl and would like to use a program a friend provide that would enable me to talk to my ham radio thru a usb/serial cable. Using W7, installed 
This is perl 5, version 14, subversion 2 (v5.14.2) built for MSWin32-x86-multi-thread
... attempts at installing this module using the perl padre graphical interface gives me this (pointing it to local download of the module):

--> Working on C:\Users\...\...\Win32-SerialPort-0.22.tar.gz
Fetching file://C:/Users/.../.../Win32-SerialPort-0.22.tar.gz ... OK
Configuring Win32-SerialPort-0.22 ... OK
Building and testing Win32-SerialPort-0.22 ...

and left with a  blinking curser. (the\ ...\ in the path replaces folder names)
as a result, a folder is created in c:.cpanm/../WIN32::SerialPort-0.22 with associated folders
running the script that calls up the serialport I get this:

Uncaught exception from user code:
        Can't locate Win32API/CommPort.pm in @INC (@INC contains: C:/Dwimperl/p
rl/site/lib C:/Dwimperl/perl/vendor/lib C:/Dwimperl/perl/lib .) at C:/Dwimperl/
erl/site/lib/Win32/SerialPort.pm line 7.
BEGIN failed--compilation aborted at C:/Dwimperl/perl/site/lib/Win32/SerialPort
pm line 7.
Compilation failed in require at sf.pl line 90.
BEGIN failed--compilation aborted at sf.pl line 90.
 at sf.pl line 90
Press any key to continue . . .

so my question...what source of information may help me figure out what I am doing wrong?
 I have read up on info on modules, FAQ. but no joy.
thanks for any pointers.
Gnuperl

**Comment by jhannah** [comment]
Looks like you need to install Win32API::CommPort? https://metacpan.org/pod/Win32API::CommPort

In any event, this github repo is for changes to the Perl Mongers website www.pm.org. We're unable to provide additional Perl support here. Thanks :)
