### ISSUE TITLE
New Group, Karlskrona

### ISSUE THREAD

**Issue by raywonteja93** [perlorg/www.pm.org#55]
Hey,

I am a student of Blekinge Institute of Technology, and a masters student
In my university, there are few hundreds of students, who deal with perl
I have got this thought to create a group.

University is located in Karlskrona, Blekinge county, Sweden

**Comment by jhannah** [comment]
Welcome! :) Here's the way to start a new group: http://www.pm.org/faq/hosting_faq.html#new
