### ISSUE TITLE
Sydney.pm

### ISSUE THREAD

**Issue by djzort** [perlorg/www.pm.org#57]
Hi there, 

We at Sydney.pm have not been able to contact Stephen in some time and no one has admin creds other than him.

Is there a process by which we can transfer admin creds to 2-3 of us?

Dean

**Comment by stennie** [comment]
@djzort FYI, stennie@cpan.org or any of the obvious addresses should work unless things are going into the spam bucket. Can you email me with who needs access to what? Thx :)

**Comment by djzort** [comment]
Must be, as i have emailed you monthly (huray cron)

**Comment by stennie** [comment]
LOL. I see Dr. Straight and Mr. Bastion somewhat regularly (both this Tuesday!) and no one mentioned ;-).

**Comment by djzort** [comment]
I am not familiar with your code names.

**Comment by stennie** [comment]
@djzort Was referring to Stuart Cooper & Alan Milligan .. long time Sydney.pm regulars

**Comment by djzort** [comment]
Stuart yes, but Alan I think ive seen once in the last 18 months. Anyway thanks.
