### ISSUE TITLE
need assitance

### ISSUE THREAD

**Issue by rohitzidu** [perlorg/www.pm.org#58]
Hi,

Need some insight who is taking care of Delhi(India) PM groups, what are meetup plans and mailing list.

Regards
Rohit

**Comment by jhannah** [comment]
Hi Rohit. Everything we think we know is here: http://www.pm.org/groups/186.html
If the group / group leader is unreachable, please let us know: http://www.pm.org/faq/hosting_faq.html#new
Thanks! :)

**Comment by rohitzidu** [comment]
Hi perl team, 

I had shoot mail two day before to delhi group members Abhishek Jain, till now I am not getting any response.
Kindly check whether he is active or not with reference id on delhi perl page.

Thanks
Rohit
+91-750-366-2776

**Comment by jhannah** [comment]
Hi Rohit. If the current group leader is unresponsive for two weeks and you're volunteering to be the new leader then we can transfer ownership to you. http://www.pm.org/faq/hosting_faq.html#new Thanks :)

**Comment by rohitzidu** [comment]
Thanks jay, Actually I have started duckduckgo quack & hack program in delhi and it will be more insight that delhi perl will be active over such great cause of perl.

I would love to volunteer the delhi perl, can you guide who will notify the same or I have to fill any form.

Thanks
Rohit
+91-750-366-2776

**Comment by jhannah** [comment]
Whatever you can do to make the Perl community stronger, great! :) Let us know how we can help.
