### ISSUE TITLE
Checked PMs near Cleveland.pm

### ISSUE THREAD

**Issue by StylusEater** [perlorg/www.pm.org#61]
I checked the following:

http://cleveland.pm.org   -- last meeting --> July 17, 2015
http://buffalo.pm.org/      -- last meeting --> February 27, 2013
http://kw.pm.org/             -- last meeting --> November 19, 2013
http://pittsburgh.pm.org/  -- SITE DOES NOT LOAD 
http://columbus.pm.org/  -- last meeting --> September 24, 2014
http://cincinnati.pm.org/   -- last meeting --> May 20th, 2015

**Comment by jhannah** [comment]
July 2015 is fine. Looks like kw updated their site. May 2015 is also fine. I deactivated the others. Thanks! :)
