### ISSUE TITLE
Zombie hunt - Fredrickton 721 

### ISSUE THREAD

**Issue by n1vux** [perlorg/www.pm.org#62]
http://www.pm.org/groups/721.html
http://fredericton.pm.org/
http://mail.pm.org/pipermail/fredericton-pm/ 

Archives have 2 months in 2013. 

Will Email Cc: the last known leaders.

**Comment by n1vux** [comment]
Brian replied "Yeah, we never really got off the ground. Ah well"

**Comment by jhannah** [comment]
So I actually don't have a problem with this. The website is friendly to visitors, links to how they could join and post messages to the mailing list immediately... quiet, but welcoming. :)
