### ISSUE TITLE
Zombie hunt - White Plains 

### ISSUE THREAD

**Issue by n1vux** [perlorg/www.pm.org#63]
Per request, checking nearest ... opening ticket for White Plains, CC: last known admin.

http://www.pm.org/groups/770.html
http://whiteplains.pm.org/
http://mail.pm.org/pipermail/whiteplains-pm/
https://twitter.com/whiteplainspm

Last email was false positive, conference promo in 2014. May 28, 2013 last tweet.

**Comment by n1vux** [comment]
Bhavin replied "You can shut this one down. We do not have any active members"

**Comment by jhannah** [comment]
Ditto on this group. If the leaders want them shut down I'm happy to do so, but I don't feel they're doing any harm. The ones I shut down proactively say awful zombie things like "Next Meeting 2002!" :)

**Comment by jhannah** [comment]
> ​Is cool.  I interpreted Zombie Hunt directive criterion as wanting proof of life to pass, not proof of undead status to fail. I hope the false positives didn't inconvenience you much. 

No worries. Thanks for your help! 

My opinion is that zombies actively screaming BRAINZ! are bad, but sleeper cells that look like they might be active and link to a mailing list anyone can immediately participate in are fine (e.g. omaha.pm.org)...  :)
