### ISSUE TITLE
Change contact for stlouis.pm.org

### ISSUE THREAD

**Issue by mkiwala** [perlorg/www.pm.org#65]
I am no longer the current group leader of stlouis.pm.org.  How can I have the group leader information changed to another individual?

PS: Even though the website hasn't been updated in quite a while, the group itself meets every month and has an active mailing list.

**Comment by jhannah** [comment]
You can submit a pull request against `perl_mongers.xml`, or just tell me who the new leader is and I can do that for you. Thanks :)

**Comment by jhannah** [comment]
Looks like #67 fixed this.
