### ISSUE TITLE
Change DNS for cleveland.pm.org

### ISSUE THREAD

**Issue by StylusEater** [perlorg/www.pm.org#69]
Please change the DNS record for cleveland.pm.org from ...

192.81.223.14

to

66.228.44.41

Thank you!

**Comment by jhannah** [comment]
DNS request submitted. Should take in a day or so. Thanks.

**Comment by StylusEater** [comment]
Thank you.

**Comment by StylusEater** [comment]
Still seems to be set to the old address.

**Comment by jhannah** [comment]
DNS request 126408 was marked complete, but I think @rspier misfired. I asked him to re-check. :)

**Comment by jhannah** [comment]
Looks fixed now. :)
