### ISSUE TITLE
What's up with the enormous, contiguous geographical area - which includes all of AL, MS, TN, AK, KT, WV, SC, KS, and nearly all of LA and MO - where there is not a single Perl Monger's group?

### ISSUE THREAD

**Issue by smoldyr** [perlorg/www.pm.org#72]
Is Atlanta really the only city in the entire, __enormous__ geographical region of the United States - consisting of nearly every Southern state except North Carolina (Florida is **_NOT_** considered a "Southern" state by other Southerners, by the way), in addition to several Midwestern states - where people use Perl? I find that hard to believe. While I understand that most Southerners aren't quite as "book smart" as those New England Ivy Leaguers or the West Coast techies (and yes, the stereotype of widespread ignorance within the Southern population is, in fact, true for the most part), there __MUST__ be enough intelligent developers within the aforementioned __enormous__ geographic area to warrant more PM groups that the current count of 0! Just for fun, It would any interesting for all Perl developers who lives within this area to respond to this "issue" and state their location. Then, we can see if the lack of PM groups does actually does correspond to a lack of Perl developers, or, if it is simply the case that people living in this area simply haven't create PM groups.

As for me, I was born, raised, and currently reside in the redneck capital of the world - Montgomery, AL.

**Comment by jhannah** [comment]
Closing since it's been 3 months w/ no response.
