### ISSUE TITLE
Update DNS for madrid.pm.org

### ISSUE THREAD

**Issue by diegok** [perlorg/www.pm.org#73]
Hi!,

we want to change the hosting of our website to a new one hosted on github pages: madridpm.github.io

Can you please set madrid.pm.org as a CNAME of madridpm.github.io ?

Thank you!
-dk

**Comment by jhannah** [comment]
Request submitted. Should take in a day or so. Thanks.

**Comment by diegok** [comment]
oh, thank you :+1:
