### ISSUE TITLE
YAPC mailing instructions needed on home page

### ISSUE THREAD

**Issue by jkeenan** [perlorg/www.pm.org#83]
The oldest mailing list associated with Yet Another Perl Conference is:  yapc@pm.org.  I know that I've been subscribed since at least 2002 -- and probably since 2000.  Granted, these days it's treated as an _unofficial_ list for discussion among conference participants, as it's neither moderated by conference organization nor, AFAIK, by the code of conduct.  I suspect that the reason why it's located at pm.org is deep inside Kevin Lenzo's brain or lost in the mists of time.

The address to subscribe to this list is:

[http://mail.pm.org/mailman/listinfo/yapc]

That's printed in the footer of every message on that list -- but when I go to [http://www.pm.org] I can't find instructions as to how to subscribe!

Could a link to the Mailman subscription page be placed, say, under *Other Useful Links*?

Thank you very much.
Jim Keenan

**Comment by jhannah** [comment]
Huh. Looks like that's the only non-pm list hosted at pm.org? http://mail.pm.org/mailman/listinfo Weird.

It is linked from yapcna.org. Isn't that the appropriate link?
