### ISSUE TITLE
hosting for baltimore.pm.org

### ISSUE THREAD

**Issue by wallisds** [perlorg/www.pm.org#84]
Can you help me re-route the baltimore.pm.org site to github? The repo is wallisds/baltimore-pm-website. Is there anything else you need?

Thanks!

**Comment by jhannah** [comment]
DNS request submitted. Should take in a day or so.

**Comment by wallisds** [comment]
Thanks for your help. I don't know if it's too soon to call or not, but the DNS hasn't updated yet as far as I can tell.

**Comment by jhannah** [comment]
Looks like it's working now. :)

**Comment by wallisds** [comment]
It works! Thanks :)
