### ISSUE TITLE
Please redirect from frankfurt.pm.org to frankfurt.pm

### ISSUE THREAD

**Issue by frankfurt-pm** [perlorg/www.pm.org#85]
Hi,

we found that frankfurt.pm.org shows old data on the web page.
Could you DNS redirect from frankfurt.pm.org to frankfurt.pm
so that the actual http://frankfurt.pm web page will be shown?

Thanks in advance, Sören

**Comment by jhannah** [comment]
It appears this is working?

**Comment by frankfurt-pm** [comment]
Hi Jay,

Am 05.09.2016 um 17:00 schrieb Jay Hannah:
>
> It appears this is working?
>
>

Yes indeed! Thank you!

Sören

-- 
Sören Laird Sörries
Tel: (069) 34 87 76 38
