### ISSUE TITLE
Please redirect purdue.pm.org to purdue.pl

### ISSUE THREAD

**Issue by jacoby** [perlorg/www.pm.org#86]
We had issues with hosting on pm.purdue.org recently and decided to switch, and also to get a new domain. Please redirect to http://purdue.pl/. 

Thanks.

**Comment by jacoby** [comment]
Made Pull Request.

**Comment by jhannah** [comment]
Looks like #90 fixed this.

**Comment by jacoby** [comment]
It doesn't.

The link on the pm.org website (http://www.pm.org/groups/238.html) goes to the desired site, but purdue.pm.org redirects to pm.purdue.org.

**Comment by jhannah** [comment]
I changed our rewritemap. Fixed now?

**Comment by jacoby** [comment]
Yup! Thanks!
