### ISSUE TITLE
Is domain "kinkeldei.de" blacklisted?

### ISSUE THREAD

**Issue by wki** [perlorg/www.pm.org#88]
Hi,
currently, I am having issues sending mails from my private domain "kinkeldei.de". Using a different domain as the sender for emails, I can successfully send mails to the erlangen.PM mailing list.
Can someone help me please?

**Comment by jhannah** [comment]
I don't think MailMan itself has any such configuration. Maybe @rspier has ideas?

**Comment by rspier** [comment]
It this is still an issue, please send an email with more detail to the support email address.
