### ISSUE TITLE
remove me from lansing.pm as moderator

### ISSUE THREAD

**Issue by xenoterracide** [perlorg/www.pm.org#89]
lansing.pm never took off and in years, afaik know one else has wanted to start it. I'm now getting moderation emails for SPAM, but I can't access my account anymore. I don't live in Michigan, I've stopped using Perl. Could you please remove xenoterracide@gmail.com as the moderator for that group? you could also remove that group entirely at your discretion.

**Comment by jhannah** [comment]
Removed from Lansing-pm config and group leader list. Thanks :)
