### ISSUE TITLE
obsolete mailing list

### ISSUE THREAD

**Issue by charlescolbourn** [perlorg/www.pm.org#98]
Hi,
I used to run Leeds.pm many years ago. It was superceded by northwestengland.pm which is looked after by the Shadowcat guys, I no longer have any involvement (and rarely write any Perl, more's the pity). I still get daily moderator requests from the pm.org mailing server though - it doesn't seem to know leeds.pm doesn't exist any more. Could someone tell it?

thanks,

Charles Colbourn

**Comment by jhannah** [comment]
Hi Charles, I removed your email address from the admin setting of that list, so that should free you. Thank you.
