### ISSUE TITLE
This is what you people do? So gross.

### ISSUE THREAD

**Issue by JoeKoen** [perlorg/www.pm.org#99]
![15086976_1786306281640159_1282218129_n](https://cloud.githubusercontent.com/assets/19499442/20417547/239d8312-ad14-11e6-9acf-8be54c4fe770.jpg)

**Comment by jhannah** [comment]
Hi Joe. No such email address exists in the pm.org domain. That message did not originate inside our organization, and we have no control over who spoofed it, or how. Click the little (i) button to get more information about who actually sent it?
